{application,bunch,
             [{applications,[kernel,stdlib,elixir]},
              {description,"A bunch of helper functions, intended to make life easier"},
              {modules,['Elixir.Bunch','Elixir.Bunch.Access',
                        'Elixir.Bunch.Binary','Elixir.Bunch.Code',
                        'Elixir.Bunch.Config','Elixir.Bunch.Enum',
                        'Elixir.Bunch.KVList','Elixir.Bunch.Macro',
                        'Elixir.Bunch.Map','Elixir.Bunch.Markdown',
                        'Elixir.Bunch.Math','Elixir.Bunch.Module',
                        'Elixir.Bunch.Retry','Elixir.Bunch.Struct',
                        'Elixir.Bunch.Type','Elixir.Bunch.Typespec']},
              {registered,[]},
              {vsn,"1.2.0"}]}.
